// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CustomModelRefreshPurpose } from "./CustomModelRefreshPurpose";

export type CustomModelRefreshParams = { purpose: CustomModelRefreshPurpose, includeHidden: boolean, };
